services:
  redis:
    image: redis:latest
  kafka:
    image: kafka:latest
  postgres:
    container_name: postgres_orders
    image: postgres:latest
    environment:
      - POSTGRES_USER: ${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB: ${POSTGRES_DB:-orders}
    volumes:
      - postges_data:/data/postgres
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge

volumes:
  postges_data:
    driver: local
